dnl -*- autoconf -*-
# Macros needed to find dune-distrib-test and dependent libraries.  They are called by
# the macros in ${top_src_dir}/dependencies.m4, which is generated by
# "dunecontrol autogen"

# Additional checks needed to build dune-distrib-test
# This macro should be invoked by every module which depends on dune-distrib-test, as
# well as by dune-distrib-test itself
AC_DEFUN([DUNE_DISTRIB_TEST_CHECKS])

# Additional checks needed to find dune-distrib-test
# This macro should be invoked by every module which depends on dune-distrib-test, but
# not by dune-distrib-test itself
AC_DEFUN([DUNE_DISTRIB_TEST_CHECK_MODULE],
[
  DUNE_CHECK_MODULES([dune-distrib-test],[distrib_test/distrib_test.hh])
])
